steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Setting project for deploy"
    args: ["gcloud", "config", "set", "project", "$_VAR_PROJECT_ID"]

  - name: "python:3.10"
    id: "Safety dependency vulnerability scanner"
    entrypoint: "bash"
    args:
      - "c"
      - |
        pip install safety
        safety check --full-report -r source/requirements.txt || true

  - name: "gcr.io/cloud-builders/docker"
    id: "Security issues Bandit"
    entrypoint: "bash"
    args:
      - "c"
      - |
        apt-get update && apt-get install -y python3-pip
        pip3 install bandit
        bandit -r . --exit-zero

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Deploy Function"
    args:
      - gcloud
      - functions
      - deploy
      - <FUNCTION-NAME>
      - --region=$_VAR_REGION
      - --source=.
      - --entry-point=main
      - --runtime=python310
      - --timeout=640
      - --memory=1024MB
      - --env-vars-file=var_env.yml
      - --vpc-connector=$_VAR_VPC_CONNECTOR
      - --trigger-topic=geokml-topic
      - --max-instances=1
      - --set-secrets=$_SECRET_01
