FROM golang:1.21 AS builder

RUN apt-get update && \
    apt-get install -y gdal-bin libgdal-dev

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=1
ENV CGO_CFLAGS="-I/usr/include/gdal"
ENV CGO_LDFLAGS="-lgdal"

RUN go build -o main .

FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y gdal-bin ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
